spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: adeline
    password: 1234Adeline!*
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
